_config:
  _metadata:
    description: caidex-v0.0.1
    name: caidex
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.0.1
  controllers:
  - containers:
    - command:
      - /app/dex
      - serve
      - /etc/dex/cfg/config.yaml
      image: '[[ g_registry_prefix_release ]]/caidex:v0.0.1'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: config
        path: /etc/dex/cfg
      name: cauth
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi
    controller:
      replicas: 1
    services:
    - name: dex
      ports:
      - nodePort: 32000
        port: 5556
        protocol: TCP
      type: NodePort
    type: Deployment
    volumes:
    - name: config
      source:
        items:
        - key: config.yaml
          path: config.yaml
        target: dex
      type: Config
