_config:
  _metadata:
    description: mysql-5.7.14
    name: mysql
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "5.7.14"
  controllers:
  - containers:
    - env:
      - name: MYSQL_DATABASE
        value: storage
      - name: DATADIR
        value: /var/lib/mysql
      - name: MYSQL_ROOT_PASSWORD
        value: 1qaz@WSX
      image: '[[ registry_library ]]/mysql:5.7.14'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: manager-data
        path: /var/lib/mysql
      ports:
      - port: 3306
        protocol: TCP
    controller:
      replica: 1
    services:
    - name: storage-manager-mysql
      ports:
      - port: 3306
        protocol: TCP
      type: ClusterIP
    type: Deployment
    volumes:
    - name: manager-data
      type: Dynamic
      source:
        class: heketi-storageclass
        modes:
        - ReadWriteMany
      storage:
        request: 4096Mi
        limit: 4096Mi
