_config:
  _metadata:
    description: helm-registry-v0.2.0
    name: helm-registry
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.2.0
  controllers:
  - containers:
    - image: '[[ g_registry_prefix_release ]]/helm-registry:v0.2.0'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: helm-registry-storage
        path: /data
      ports:
      - port: 8099
        protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
    controller:
      replicas: 1
    initContainers:
    - env:
      - name: FORCE_UPDATE
        value: 'true'
      - name: OUTPUT_DIR
        value: /data/system-tenant_library
      - name: IMAGE_DOMAIN
        value: '[[ default_cargo ]]'
      image: '[[ g_registry_prefix_release ]]/charts:v1.2.0-alpha.1'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: helm-registry-storage
        path: /data
      name: charts
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
    services:
    - name: helm-registry
      ports:
      - port: 8099
        protocol: TCP
        targetPort: 8099
      type: ClusterIP
    type: Deployment
    volumes:
    - name: helm-registry-storage
      source:
        target: helm-registry-charts-data
      type: Static
