_config:
  _metadata:
    description: fluentd-elasticsearch-v2.0.1
    name: fluentd-elasticsearch
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v2.0.1
  controllers:
  - containers:
    - env:
      - name: FLUENTD_ARGS
        value: --no-supervisor -q
      - name: CLUSTER_ID
        value: http://cds-server:9000/addon-manager
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      image: '[[ g_registry_prefix_release ]]/fluentd-elasticsearch:v2.0.1'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: varlog
        path: /var/log
      - name: varlibdockercontainers
        path: /var/lib/docker/containers
        readonly: true
      - name: libsystemddir
        path: /host/lib
        readonly: true
      - name: config-volume
        path: /etc/fluent/config.d
      ports:
      - port: 24231
        protocol: TCP
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 200m
          memory: 200Mi
    controller: null
    services:
    - name: fluentd-logging
      ports:
      - annotations:
          prometheus.io/port: '24231'
          prometheus.io/scrape: 'true'
        port: 8080
        protocol: TCP
    type: DaemonSet
    volumes:
    - name: varlog
      source:
        path: /var/log
      type: HostPath
    - name: varlibdockercontainers
      source:
        path: /var/lib/docker/containers
      type: HostPath
    - name: libsystemddir
      source:
        path: /usr/lib64
      type: HostPath
    - name: config-volume
      source:
        target: fluentd-es-config
      type: Config
