_config:
  _metadata:
    description: devops-admin
    name: devops-admin
    namespace: default
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v0.8.0-alpha"
  controllers:
  - containers:
    - image: '[[ registry_release ]]/devops-admin:v0.8.0-alpha'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: config
        path: /app/etc
      ports:
      - port: 7088
        protocol: TCP
    controller:
      replica: 1
    services:
    - name: devops-admin
      ports:
      - port: 7088
        protocol: TCP
        targetPort: 7088
      type: ClusterIP
    type: Deployment
    volumes:
    - name: config
      source:
        target: devops-admin-config
        items:
        - key: devops-admin.json
          path: devops-admin-config.json
      type: Config
    configs:
    - name: devops-admin-config
      data:
      - key: devops-admin.json
        value: |
          {
            "logging": {
              "level": "info"
            },
            "host": "0.0.0.0",
            "port": 7088,
            "addresses": {
              "cycloneServer": "cyclone-server:7099",
              "storageAdmin": "storage-admin:2333",
              "clusterAdmin": "cds-server:9000",
              "cargoAdmin": "cargo-admin:8080",
              "tenantAdmin": "tenant-admin:8080",
              "notifyAdmin": "notify-admin:8900"
            }
          }
