_config:
  _metadata:
    description: elasticsearch_exporter-1.0.1
    name: exporters-elasticsearch
    namespace: kube-system
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "1.0.1"
  controllers:
  - containers:
    - command:
      - /bin/elasticsearch_exporter
      - -es.uri=http://elasticsearch:9200
      - -es.all=true
      image: '[[ registry_release ]]/elasticsearch_exporter:1.0.1'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 9108
        protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 25m
          memory: 64Mi
    controller:
      replica: 1
    services:
    - annotations:
      - key: prometheus.io/port
        value: '9108'
      - key: prometheus.io/scrape
        value: 'true'
      name: elasticsearch-exporter
      ports:
      - port: 9108
        protocol: TCP
      type: ClusterIP
    type: Deployment
