apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flavors.clever.caicloud.io
spec:
  group: clever.caicloud.io
  names:
    kind: Flavor
    listKind: FlavorList
    plural: flavors
    singular: flavor
  scope: Cluster
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: templates.clever.caicloud.io
spec:
  group: clever.caicloud.io
  names:
    kind: Template
    listKind: TemplateList
    plural: templates
    singular: template
  scope: Cluster
  version: v1alpha1

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projects.clever.caicloud.io
spec:
  group: clever.caicloud.io
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  version: v1alpha1
