apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: flavors.clever.caicloud.io
spec:
  group: clever.caicloud.io
  names:
    kind: Flavor
    listKind: FlavorList
    plural: flavors
    singular: flavor
  scope: Cluster
  version: v1alpha1
