apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flavors.clever.caicloud.io
spec:
  group: clever.caicloud.io
  names:
    kind: Flavor
    listKind: FlavorList
    plural: flavors
    singular: flavor
  scope: Cluster
  version: v1alpha1

---

apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: python
spec:
  images:
  - name: Python2
    image: '[[ registry_release ]]/pytorch:v0.4.1-py27'
  - name: Python3
    image: '[[ registry_release ]]/pytorch:v0.4.1-py36'
  resources:
  - name: basic
    cpu: "1"
    gpu: "0"
    memory: 2048Mi
  - name: standard
    cpu: "2"
    gpu: "0"
    memory: 4096Mi
  - name: advanced
    cpu: "2"
    gpu: "1"
    memory: 4096Mi

---

apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: pytorch
spec:
  images:
  - name: Python2+PyTorch0.4
    image: '[[ registry_release ]]/pytorch:v0.4.1-py27'
  - name: Python3+PyTorch0.4
    image: '[[ registry_release ]]/pytorch:v0.4.1-py36'
  resources:
  - name: basic
    cpu: "1"
    gpu: "0"
    memory: 1024Mi
  - name: standard
    cpu: "2"
    gpu: "0"
    memory: 4096Mi
  - name: advanced
    cpu: "2"
    gpu: "1"
    memory: 4096Mi

---

apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: tensorflow
spec:
  images:
  - name: Python2+TensorFlow1.4
    image: '[[ registry_release ]]/tensorflow:v1.4.1-py27'
  - name: Python3+TensorFlow1.4
    image: '[[ registry_release ]]/tensorflow:v1.4.1-py36'
  - name: Python2+TensorFlow1.9
    image: '[[ registry_release ]]/tensorflow:v1.9.0-py27'
  - name: Python3+TensorFlow1.9
    image: '[[ registry_release ]]/tensorflow:v1.9.0-py36'
  resources:
  - name: basic
    cpu: "1"
    gpu: "0"
    memory: 2048Mi
  - name: standard
    cpu: "2"
    gpu: "0"
    memory: 4096Mi
  - name: advanced
    cpu: "2"
    gpu: "1"
    memory: 4096Mi

---

apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: jupyter
spec:
  images:
  - image: '[[ registry_release ]]/anaconda:v5.2.0'
    name: jupyterLab
  - image: '[[ registry_release ]]/anaconda:v5.2.0'
    name: jupyterNotebook
  resources:
  - cpu: "1"
    gpu: "0"
    memory: 1024Mi
    name: basic
  - cpu: "2"
    gpu: "0"
    memory: 4096Mi
    name: standard
  - cpu: "2"
    gpu: "1"
    memory: 4096Mi
    name: advanced

---

apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: spark
spec:
  images:
  - image: '[[ registry_release ]]/spark:v2.4.0'
    name: spark2.4.0
  resources:
  - cpu: "1"
    gpu: "0"
    memory: 1024Mi
    name: basic
  - cpu: "2"
    gpu: "0"
    memory: 2048Mi
    name: standard
  - cpu: "2"
    gpu: "0"
    memory: 4096Mi
    name: advanced

---

apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: keras
spec:
  images:
  - image: '[[ registry_release ]]/keras:v2.1.3-py27'
    name: keras-python2
  - image: '[[ registry_release ]]/keras:v2.1.3-py36'
    name: keras-python3
  resources:
  - cpu: "1"
    gpu: "0"
    memory: 1024Mi
    name: basic
  - cpu: "2"
    gpu: "0"
    memory: 2048Mi
    name: standard
  - cpu: "2"
    gpu: "1"
    memory: 4096Mi
    name: advanced

---

apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: caffe
spec:
  images:
  - image: '[[ registry_release ]]/caffe:py27'
    name: caffe-python2
  - image: '[[ registry_release ]]/caffe:py36'
    name: caffe-python3
  resources:
  - cpu: "1"
    gpu: "0"
    memory: 1024Mi
    name: basic
  - cpu: "2"
    gpu: "0"
    memory: 2048Mi
    name: standard
  - cpu: "2"
    gpu: "1"
    memory: 4096Mi
    name: advanced

---

apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: sklearn
spec:
  images:
  - image: '[[ registry_release ]]/sklearn:py27'
    name: Sklearn-Python2
  - image: '[[ registry_release ]]/sklearn:py36'
    name: Sklearn-Python3
  resources:
  - cpu: "1"
    gpu: "0"
    memory: 1024Mi
    name: basic
  - cpu: "2"
    gpu: "0"
    memory: 2048Mi
    name: standard
  - cpu: "2"
    gpu: "0"
    memory: 4096Mi
    name: advanced
