apiVersion: clever.caicloud.io/v1alpha1
kind: Flavor
metadata:
  name: tensorflow
spec:
  images:
  - name: Python2+TensorFlow1.4
    image: '[[ registry_release ]]/tensorflow:v1.4.1-py27'
  - name: Python3+TensorFlow1.4
    image: '[[ registry_release ]]/tensorflow:v1.4.1-py36'
  - name: Python2+TensorFlow1.9
    image: '[[ registry_release ]]/tensorflow:v1.9.0-py27'
  - name: Python3+TensorFlow1.9
    image: '[[ registry_release ]]/tensorflow:v1.9.0-py36'
  resources:
  - name: basic
    cpu: "1"
    gpu: "0"
    memory: 2048Mi
  - name: standard
    cpu: "2"
    gpu: "0"
    memory: 4096Mi
  - name: advanced
    cpu: "2"
    gpu: "1"
    memory: 4096Mi
