_config:
  _metadata:
    description: cargo-admin-v0.3.3
    name: cargo-admin
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.3.3
  controllers:
  - containers:
    - image: '[[ g_registry_prefix_release ]]/cargo-admin:v0.3.3'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: cargo-admin-config
        path: /app/etc
    controller:
      replicas: 1
    services:
    - name: cargo-admin-nodeport
      ports:
      - nodePort: 30099
        port: 8081
        protocol: TCP
        targetPort: 8081
      type: NodePort
    - name: cargo-admin
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      type: ClusterIP
    type: Deployment
    volumes:
    - name: cargo-admin-config
      source:
        items:
        - key: cargo-admin-config.json
          path: cargo-admin-config.json
        - key: private_key.pem
          path: private_key.pem
        target: cargo-admin-config
      type: Config
