_config:
  _metadata:
    description: postgres-9.5.8
    name: postgres
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "9.5.8"
  controllers:
  - containers:
    - env:
      - name: POSTGRES_USER
        value: dex
      - name: POSTGRES_PASSWORD
        value: hahahaha
      - name: PGDATA
        value: /var/lib/postgresql/data/pgdata
      - name: POSTGRES_DB
        value: dex_db
      image: '[[ registry_release ]]/postgres:9.5.8'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: dex-storage
        path: /var/lib/postgresql/data
      ports:
      - port: 5432
        protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi
    controller:
      replica: 1
    services:
    - name: dex-postgres
      ports:
      - port: 5432
        protocol: TCP
        targetPort: 5432
      type: ClusterIP
    type: Deployment
    volumes:
    - name: dex-storage
      type: Dynamic
      source:
        class: heketi-storageclass
        modes:
        - ReadWriteMany
      storage:
        request: 4096Mi
        limit: 4096Mi
