_config:
  _metadata:
    description: canary-controller-v0.2.0
    name: canary-controller
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.2.0
  controllers:
  - containers:
    - args:
      - --debug
      - --proxy-image=[[ g_registry_prefix_release ]]/canary-nginx-proxy:v0.2.0
      image: '[[ g_registry_prefix_release ]]/canary-controller:v0.2.0'
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 200m
          memory: 200Mi
    controller:
      replicas: 1
    type: Deployment
