_config:
  _metadata:
    description: monitoring-admin-v0.5.2
    name: monitoring-admin
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.5.2
  controllers:
  - containers:
    - args:
      - /admin
      - --mongo-endpoint=$(MONGO_ENDPOINT)
      env:
      - from:
          key: monitoring-admin.mongo-server
          name: generic-config
          type: Config
        name: MONGO_ENDPOINT
      - from:
          key: monitoring-admin.cds-server
          name: generic-config
          type: Config
        name: CLUSTER_ADMIN
      image: '[[ g_registry_prefix_release ]]/monitoring-admin:v0.5.2'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 8899
        protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 1.5Gi
        requests:
          cpu: 100m
          memory: 256Mi
    controller:
      replicas: 1
    pod:
      serviceAccountName: admin
    services:
    - name: monitoring-admin
      ports:
      - port: 8899
        protocol: TCP
      type: ClusterIP
    type: Deployment
