_config:
  _metadata:
    description: caidex-v2.6.2
    name: dex-caidex
    namespace: default
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v2.6.2"
  controllers:
  - containers:
    - command:
      - /app/dex
      - serve
      - /etc/dex/cfg/config.yaml
      image: '[[ registry_release ]]/caidex:v2.6.2'
      imagePullPolicy: IfNotPresent
      env:
      - name: ISSUER
        from:
          type: Config
          name: platform-config
          key: "oidcIssuer"
      - name: CAICLOUD_REDIRECT_URI
        from:
          type: Config
          name: platform-config
          key: "oidcRedirectURIs"
      - name: CLUSTER_REDIRECT_URI
        from:
          type: Config
          name: platform-config
          key: "oidcRedirectURIs"
      mounts:
      - name: config
        path: /etc/dex/cfg
      name: cauth
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 500m
          memory: 500Mi
    controller:
      replica: 1
    services:
    - name: dex
      ports:
      - nodePort: 32000
        port: 5556
        protocol: TCP
      type: NodePort
    type: Deployment
    volumes:
    - name: config
      source:
        items:
        - key: config.yaml
          path: config.yaml
        target: dex
      type: Config
    configs:
    - name: dex
      data:
      - key: config.yaml
        value: |
            issuer: "<ISSUER>"
            oauth2:
              skipApprovalScreen: true
              scopes:
              - tenants
            storage:
              type: postgres
              config:
                host: dex-postgres
                database: dex_db
                user: dex
                password: hahahaha
                ssl:
                  mode: disable
            web:
              http: 0.0.0.0:5556
            grpc:
              addr: 127.0.0.1:5557
            expiry:
              signingKeys: "6h"
            enablePasswordDB: false
            staticClients:
            - name: 'caicloud'
              redirectURIs: ["<CAICLOUD_REDIRECT_URI>"]
              id: caicloud
              secret: caicloud
            - name: 'cluster'
              redirectURIs: ["<CLUSTER_REDIRECT_URI>"]
              id: cluster
              secret: cluster
              trustedPeers:
              - caicloud
            mainConnector: cauth
            connectors:
            # used to avoid a bug
            - type: github
              id : github
              name: github
            [[ dex.disable_cauth_connector ]]- type: cauth
            [[ dex.disable_cauth_connector ]]  id: cauth
            [[ dex.disable_cauth_connector ]]  name: Cauth
            [[ dex.disable_cauth_connector ]]  config:
            [[ dex.disable_cauth_connector ]]    host: "dex-cauth:8080"
            [[ dex.disable_haier_connector ]]- type: haier
            [[ dex.disable_haier_connector ]]  id: haier
            [[ dex.disable_haier_connector ]]  name: haier
            [[ dex.disable_haier_connector ]]  config:
            [[ dex.disable_haier_connector ]]    clientID: "[[ dex.haier_client_id ]]"
            [[ dex.disable_haier_connector ]]    clientSecret: "[[ dex.haier_client_secret ]]"
            [[ dex.disable_haier_connector ]]    redirectURI: "[[ dex.oidc_issuer ]]/callback"
            [[ dex.disable_haier_connector ]]    url: "[[ dex.haier_host ]]"
