_config:
  _metadata:
    description: tenant-controller-v1.1.0-alpha.1
    name: tenant-controller
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v1.1.0-alpha.1
  controllers:
  - containers:
    - image: '[[ g_registry_prefix_release ]]/tenant-controller:v1.1.0-alpha.1'
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 200Mi
        requests:
          cpu: 500m
          memory: 200Mi
    controller:
      replicas: 1
      strategy:
        surge: 1
        unavailable: 0
    type: Deployment
