_config:
  _metadata:
    description: tf-operator-v1alpha2-v1.0.0
    name: tf-operator
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v1.0.0"
  controllers:
  - containers:
    - image: '[[ registry_release ]]/tf-operator:v1alpha2-v1.0.0'
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
    controller:
      replica: 1
    initContainers:
    - image: '[[ registry_release ]]/tf-operator-crd:v1.0.0'
      imagePullPolicy: IfNotPresent
    pod:
      serviceAccountName: admin
    type: Deployment
