_config:
  _metadata:
    description: kubeflow-admin-v1.0.1
    name: kubeflow-admin
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v1.0.4"
  controllers:
  - containers:
    - env:
      - name: KUBEFLOW_ADMIN_POSTGRESQL
        value: postgres://postgres:7c6fa0e1ec027acc14afc0f0@kubeflow-admin-postgres:5432/postgres?sslmode=disable
      - name: IMAGE_PREFIX
        value: '[[ registry_release ]]'
      - name: APP_ADMIN
        value: http://app-admin:7799
      - name: STORAGE_MANAGER
        value: http://storage-manager:4500
      - name: KUBE_ENDPOINT_IP
        value: '[[ kube_apiserver_endpoint_ip ]]'
      - name: KUBE_APISERVER
        value: '[[ kube_apiserver_endpoint_ip ]]:6442'
      - name: KUBE_USERNAME
        value: '[[ kube_username ]]'
      - name: KUBE_PASSWORD
        value: '[[ kube_password ]]'
      image: '[[ registry_release ]]/kubeflow-admin:v1.0.4'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 8080
        protocol: TCP
    controller:
      replica: 1
    initContainers:
    - args:
      - sh
      - -c
      - until nslookup kubeflow-admin-postgres; do echo waiting for mydb; sleep 2;
        done;
      image: '[[ registry_release ]]/alpine:3.6'
      imagePullPolicy: IfNotPresent
    - args:
      - admin
      - migrate
      - up
      env:
      - name: KUBEFLOW_ADMIN_POSTGRESQL
        value: postgres://postgres:7c6fa0e1ec027acc14afc0f0@kubeflow-admin-postgres:5432/postgres?sslmode=disable
      image: '[[ registry_release ]]/kubeflow-admin:v1.0.4'
      imagePullPolicy: IfNotPresent
    pod:
      serviceAccountName: admin
    schedule:
      antiaffinity:
        pod:
          terms:
          - selector:
              labels:
                caicloud-app: kubeflow-admin
            topologyKey: kubernetes.io/hostname
            weight: 100
          type: Prefered
      labels:
        caicloud-app: kubeflow-admin
    services:
    - name: kubeflow-admin
      ports:
      - port: 8080
        protocol: TCP
      type: ClusterIP
    type: Deployment
