_config:
  _metadata:
    description: console-web
    name: console-web-web
    namespace: default
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v3.2.3"
  controllers:
  - containers:
    - env:
      - name: MONGODB_URL
        value: '[[ platform_mongo_host ]]'
      - name: HIDE_MENU
        value: caas_circle
      - name: HIDE
        value: forget
      - name: CLOUD_ENV
        value: private
      - name: CLUSTER_ENV
        value: '50'
      - name: FORNAX_LOG_ENV
        value: ws://[[ kube_apiserver_endpoint_ip ]]:30070
      - name: OEM_ENV
        value: '0'
      - name: HODOR_SERVER
        value: http://hodor:8080
      - name: EXTERNAL_HODOR
        from:
          type: Config
          name: platform-config
          key: "hodorEndpoint"
      - name: MONITOR_SERVER
        value: http://monitoring-admin:8899/api/v1
      - name: MANUAL_URL
        value: http://[[ kube_apiserver_endpoint_ip ]]:30040
      - name: _CAAS_SERVER
        value: '[[ kube_apiserver_endpoint_ip ]]:30000'
      - name: CAICLOUD_PRODUCT_CFG_STRING_MULTI_TENANCY
        from:
          type: Config
          name: platform-config
          key: "tenantMode"
      - name: CPS_ENDPOINT
        from:
          type: Config
          name: platform-config
          key: "compassWebEndpoint"
      - name: DEX_SERVER
        # should use internal dex server ip
        from:
          type: Config
          name: platform-config
          key: "oidcIssuer"
      - name: ISSUER
        from:
          type: Config
          name: platform-config
          key: "oidcIssuer"
      - name: OIDC_CLIENT_ID
        value: caicloud
      - name: OIDC_CLIENT_SECRET
        value: caicloud
      - name: OIDC_REDIRECT_URI
        value: /api/idToken
      - name: SHOW_LANG
        value: 'false'
      - name: DEFAULT_LANG
        value: 'zh-cn'
      # Get release info from system-info ConfigMap
      - name: PRODUCT_VERSION
        value: '[[ platform_release_version ]]'
      - name: PRODUCT_RELEASE_TIME
        value: '[[ platform_release_time ]]'
      image: '[[ registry_release ]]/console-web:v3.2.3'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 3000
        protocol: TCP
    controller:
      replica: 1
      strategy:
        surge: 1
        unavailable: 0
    services:
    - name: console-web
      ports:
      - nodePort: 30000
        port: 3000
        protocol: TCP
      type: NodePort
    type: Deployment
