_config:
  _metadata:
    description: cargo-admin-v0.3.6
    name: cargo-admin
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v0.3.18"
  controllers:
  - type: Deployment
    controller:
      replica: 1
    containers:
    - image: '[[ registry_release ]]/cargo-admin:v0.3.18'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: cargo-admin-config
        path: /app/etc
      - name: cargo-admin-docker-sock
        path: /var/run/dind
    - image: '[[ registry_release ]]/docker:1.13.1-dind'
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      args:
        - dockerd
        - -H unix:///var/run/dind/docker.sock
      mounts:
      - name: cargo-admin-docker
        path: /var/lib/docker
      - name: cargo-admin-docker-sock
        path: /var/run/dind
    services:
    - name: cargo-admin-nodeport
      ports:
      - nodePort: 30099
        port: 8081
        protocol: TCP
        targetPort: 8081
      type: NodePort
    - name: cargo-admin
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      type: ClusterIP
    volumes:
    - name: cargo-admin-config
      source:
        items:
        - key: cargo-admin-config.json
          path: cargo-admin-config.json
        - key: private_key.pem
          path: private_key.pem
        target: cargo-admin-config
      type: Config
    - name: cargo-admin-docker
      source:
        medium: ''
      type: Scratch
    - name: cargo-admin-docker-sock
      source:
        medium: ''
      type: Scratch
    configs:
    - name: cargo-admin-config
      data: 
      - key: cargo-admin-config.json
        value: |
          {
            "mongo": {
              "addrs": "[[ platform_mongo_host ]]",
              "db": "cargo_admin",
              "mode": "strong"
            },
            "tenant": {
              "multi_tenant": "[[ multi_tenant ]]",
              "system_tenant": "system-tenant"
            },
            "project": {
              "default_public_projects": [
                {
                  "name": "library",
                  "if_exists": "force",
                  "harbor":"default"
                },
                {
                  "name": "release",
                  "if_exists": "force",
                  "harbor":"default"
                }
              ]
            },
            "registry": {
              "global": {
                "private_key": "./etc/private_key.pem",
                "cauth_host": "http://dex-cauth:8080",
                "token_expiration": 30
              },
              "default": {
                "host": "https://[[ cargo_registry ]]",
                "username": "admin",
                "password": "Pwd123456"
              }
            },
            "service": {
              "addr": "0.0.0.0:8080",
              "service_token_addr": "0.0.0.0:8081"
            }
          }
      - key: private_key.pem
        value: |
          -----BEGIN RSA PRIVATE KEY-----
          MIIJKQIBAAKCAgEA4j85U1ql3f/OGy5vIZUUFKA84AbPz4LmmK6XbfRP1f89wktV
          t0nsq0/t0Mnc95ugZW3HPq38tFLAs29lhl/wzPG5+2JcgQTeO4b/uHWfE/Pr5oV+
          f7YRO2ltUV+BX2Spr3BlLPFOGdRZ86KFq+4U0E+BOlTvcmIpBTuXDlNHxzsSsD2M
          ScnyMdQzsE7g7Rr+ZmRy5jFWBLYp0SUW97t4G9O/F7cGAW734SqDq0TLec2V9ekX
          k0u64C8ozOxc+jcE+F5vMBICImUoIaxoAj4UuN0E+yV7Rzj4NyZ1xc0E16khPxKN
          hTpQ8NlBmNHszNbJ5X7tTDJx7OSMIX9tlRTMFBXyfPu0sdkWMGRHf87QS93oHXYm
          qvMZHwGffeo4xh7QVo1uszIxfnkmporbL6KNBs49xOjzk+NSnQeqKWjCgICBilBw
          0t7ocM3Qrl7JO1yuGNd/Z0/pX/NE1BrtPGltmH9TVc6Ir0VomDAG7U4VY1r+otiG
          Rzszz/zLwCPr7hNhLABLuz87MK/js4ya2yXfkUnJtv+QU/xVtoMVj/L+IbNotheV
          e1BOpU0xqw/Xr9GUwOSNug246UwDeO95JJcUkJ1VtiMZJ/SJQ7ImNUpVmlJ7GOzF
          icNc+Fm7zIR5Xfrlx74ZaxoRKqDb2pX69WjXFh8zOlGUMh88MT/OggPJmKsCAwEA
          AQKCAgBmk0WZTgLfmMfIORA3iJB3HYMcCtqS+YU0+gs71cWQf01v1poBJKoBrZZj
          z/G37T4WXmQ0PcvRsacec0XzW3IgaQPqPlk0QZHEKVutNN6vvCpa9HE608ASUKU4
          fHV6W3g3S10DuE+xlD5IIIo8Pg//tdwgJzv8fxacAb1lyEpFwLmjX/RHzCBbiRr6
          N3jw5wkqQSZ6ySl3r2NcKFW2ca9t5l3AEcHOSpJl6tGRh/o8ugHgYRLIPFB4rcjw
          x8ULyIAfXylIARIop/Y+9hydz6mzerl0aDTxQJoA3xYMXPxyDoM9RlsVaTAjUkzU
          TXDwGf2laBuMLV7LiX8i/NQhADHZmzFYOuJEK4D39ofaTkUMNk2JFoazbQ5FTPMy
          rbIPNG0YY1np68XyB258JBwX2PKJvE2DhP5tcrJL7HzIwKBC9C3K8OpTJunK4S7P
          i9IfMPzflX6exWI9ak0E5zPeyH0HZLGFkPthDyu7pQWg6DkivVi39Y2pQp2UQoUo
          T/+gZo8Q/c5RfCROva9RXoVon/nyIEBUoCCXqJ/Pw9VwVd7d/GDIf/4zJNxVZpom
          /yTqVd2l3fYbjcki6W1mxg72qXPukwXUtzpC5bXvNqtKLm+WeRVxhItHI2NHiB3E
          ucZO4jjrLEKWnBripqefVG2lnQRAg584Lh4djWLQA3j5r4r9eQKCAQEA8uDMpKwr
          90TzltAFMSmPCbpgawYMWioAJmd3XUrDwQsVCmlOmQ9mKULN4y+jZRqRdGOd5x20
          3L7Fn5HmKac9tukbBRnLi0hkYiEac6EagHLAoUsvbHAxyX9swwp55MRAI7yIHas5
          y2ELr1wd8KiRvaErQOuIFODCKidaeaOXrVJskBRHCcQTp39eAOSMNo6C1lV5gOFx
          yt3mUMCYbnLySwzoOeNDmHqRjSz7MAt6SUaSrXberffU4APc1gcHZXrHuPZY2O7i
          zY+9uQG/8uuf76GGQHLnPDENP4tkHbvwyOQsQpBkk/jDCjRWkzi6bVsGlRSkb0iV
          1H4znPWVBpe9jwKCAQEA7nhm+Y6Bk4Hs6bpdUAUyVgvQmcfEACCqq8JLYflL924T
          HLKeeREFLo0deyruobJdPKJMRkm/07Qi9cZZwYXpDPJvFNfOybsAGa8Jj7HZ5C8A
          e6DEFYoYRBAKTMGUp0f/KUYWvVLs/5NVHS/1YzbpC6AoutZryAAg3xRpewjGjpc5
          q9ONPgXD+MVj5HKfJx/k4NX2EPfcYmSSKFgwDTsexL0exReW54nTBTuHnmwNmazG
          dYCGVmIIiS+bPhLX6S4fOyE0N8d/fWIyYvTxmavP1fLSDzLws6ARbi54e3Xmxr3m
          vVpjtuhvKDcY7wdhTuLk0KiyocCOFsBkIHB5vX4dJQKCAQEArG5s23xgumx5g9ir
          1vtqUb3ANjtVCa5H7PwIAnPSBnuXtIyPAJuuLB0BjwmDN4RlP/x5Xlv4y7+lDmTG
          w0u4xOM6C6UEnR4IJqLZ5L270vWlTN3UDWiZ8DRHQzFs2L17y+NNv8KQhZOgeB8u
          Im2LCtYhnzWYpznqn4LQ+Qrr5GFgMeozhPtv+Lq0Qm4AHbuPqBuG57km0KA5o5sY
          nVF+M0o2lOKEWvyp2VDWBIYhi2RPPlfmQBxzRZd4cXsMBT/mC6rZ6SmwW8BxMafM
          Xupp4fcLGTZ6dIFepn6P1YxYpkdYJOnefi9eSSBfVqYvtPOq+KxvEZK2zOXMPuMb
          qlKQgQKCAQEAzHDqjz5N9iDn9ATy5Jxf6AbfAkeR0C4xQ2kh6U+pgembdvnnBJHD
          6IHQaXyH8pYQeuAFFik5zIxdgGlZH6DnCFN7SdouDSJFVr+KKefmjkqBVnugP3sR
          jKBXxDAdekAuD7tn2U2ToxQzXv9zl2hG6NGYuX0EEAWUKMu+Fl2SpEIfjiCisS6O
          MONA3WQq74bXWK3189wa0zu3VeEs6NrraO1dyMiNddjh0VWU0gt+qWXHCotyH/KR
          sNLge5n6Ao2o9q9jrgJZWSvrWIz356+1UY2H6sHYO5aZ+uTaI7YTcAT0IRex7uhc
          C5UYyiuAj/nTAtPtuOB0sCqmbG0g4YSSBQKCAQAHuKLF4/bO2l9tiHO+ORVjSVQF
          En1MYd9sobexDUHuaWs9aFYxLr6iLdf2aFnj0HnExJ+QyCBv25Wdcx4ONC6BETrF
          f1JqeEBF5ybhgmaJ8nSpz3xJ6TPoJvVm9UOkLDQvb8zJE7xBIyH1xjKsPFPymbeB
          NCE3PMH+/qXCGcyhEXvcdb1m7LaOeFQGg43eVzZk/4yuYcY630h+MlybNEF2xrqN
          v89Pd1gNomfS3lCVKRz9y1XV2O/zMB8waUhRUdnylIiXjcN/RstfFE2nQHb5816z
          RPj9HM0KDl+gMO7wFwougDvvWyZ+gpIzh6nMU83ewBm755v0RKWLJDg/CvEH
          -----END RSA PRIVATE KEY-----
