_config:
  _metadata:
    description: app-admin-v0.2.6
    name: app-admin
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.2.6
  controllers:
  - containers:
    - env:
      - from:
          key: app-admin.helm-registry
          name: generic-config
          type: Config
        name: HELM_REGISTRY_HOST
      image: '[[ g_registry_prefix_release ]]/app-admin:v0.2.6'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 7799
        protocol: TCP
    controller:
      replica: 1
    services:
    - name: app-admin
      ports:
      - port: 7799
        protocol: TCP
      type: ClusterIP
    type: Deployment
