_config:
  _metadata:
    description: config-reference-v0.1.6
    name: config-reference
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.1.6
  controllers:
  - containers:
    - image: '[[ g_registry_prefix_release ]]/config-reference:v0.1.6'
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 300m
          memory: 300Mi
        requests:
          cpu: 200m
          memory: 200Mi
    controller:
      replicas: 1
    type: Deployment
