_config:
  _metadata:
    description: cluster-admin
    name: cluster-admin
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v1.1.0-alpha.9"
  controllers:
  - containers:
    - env:
      - name: ENV_LISTEN_PORT
        value: '2233'
      - name: ENV_LOG_LEVEL
        value: info
      - name: ENV_MONGO_ADDR
        value: cds-mongo:27017
      image: '[[ registry_release ]]/cluster-admin:v1.1.0-alpha.9'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 2233
        protocol: TCP
    controller:
      replica: 1
      strategy:
        surge: 1
        unavailable: 0
    pod:
      serviceAccountName: admin
    services:
    - name: cds-server
      ports:
      - port: 9000
        protocol: TCP
        targetPort: 2233
      type: ClusterIP
    - name: cluster-admin
      ports:
      - port: 2233
        protocol: TCP
      type: ClusterIP
    type: Deployment
