_config:
  _metadata:
    description: kube-state-metrics-release-v1.1.0
    name: kube-state-metrics
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: release-v1.1.0
  controllers:
  - containers:
    - image: '[[ g_registry_prefix_release ]]/kube-state-metrics:release-v1.1.0'
      imagePullPolicy: IfNotPresent
      name: kube-state-metrics
      ports:
      - port: 8080
        protocol: TCP
      probe:
        readiness:
          delay: 5
          handler:
            method:
              path: /healthz
              port: 8080
            type: HTTP
          timeout: 5
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
    - command:
      - /pod_nanny
      - --container=kube-state-metrics
      - --cpu=100m
      - --extra-cpu=1m
      - --memory=100Mi
      - --extra-memory=2Mi
      - --threshold=5
      - --deployment=kube-state-metrics
      downwardPrefix: MY_
      image: '[[ g_registry_prefix_release ]]/addon-resizer:release-1.0'
      imagePullPolicy: IfNotPresent
      name: addon-resizer
      resources:
        limits:
          cpu: 100m
          memory: 30Mi
        requests:
          cpu: 100m
          memory: 30Mi
    controller:
      replica: 1
    services:
    - name: kube-state-metrics
      ports:
      - port: 8080
        protocol: TCP
        targetPort: http-metrics
      type: ClusterIP
    type: Deployment
