_config:
  _metadata:
    description: alert-notifier-v0.4.1
    name: alert-notifier
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.4.1
  controllers:
  - containers:
    - args:
      - -config=/etc/alert-notifier/notifier.yaml
      env:
      - from:
          key: alert-notifier.monitoring-admin-mongo
          name: generic-config
          type: Config
        name: MONGO_ENDPOINT
      image: '[[ g_registry_prefix_release ]]/alert-notifier:v0.4.1'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: notifier-config
        path: /etc/alert-notifier
      ports:
      - port: 5001
        protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 20m
          memory: 50Mi
    controller:
      replicas: 1
    services:
    - name: alert-notifier
      ports:
      - port: 5001
        protocol: TCP
        targetPort: 5001
      type: ClusterIP
    type: Deployment
    volumes:
    - name: notifier-config
      source:
        default: 420
        target: alert-notifier
      type: Secret
