_config:
  _metadata:
    description: storage-manager-v1.4.2
    name: clever-storage-manager
    namespace: default
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v1.4.2"
  controllers:
  - containers:
    - env:
      - name: APP_ADMIN_URL
        value: http://app-admin:7799/api/v1
      - name: VOLUME_ROOT_PATH
        value: /clever
      - name: FILESERVER_IMAGE
        value: '[[ registry_release ]]/storage-fileserver:v1.3.1'
      - name: FILESERVER_LIMITS_CPU
        value: '2'
      - name: FILESERVER_LIMITS_MEMORY
        value: '4'
      - name: FILESERVER_REQUESTS_CPU
        value: '0.1'
      - name: FILESERVER_REQUESTS_MEMORY
        value: '0.1'
      - name: FILESERVER_VOLUME_COUNT
        value: '2'
      - name: KUBE_CLUSTER_ID
        value: ""
      - name: KUBE_CLUSTER_OWNER_ID
        value: '123456'
      - name: KUBE_HOST
        value: '[[ kube_apiserver_endpoint_ip ]]:6442'
      - name: KUBE_USER
        value: '[[ kube_username ]]'
      - name: KUBE_PASSWORD
        value: '[[ kube_password ]]'
      - name: POLL_INTERVAL_SECOND
        value: '30'
      - name: STORAGE_KUBE_NAMESPACE
        value: default
      - name: STORAGE_MYSQL_DB_STRING
        value: root:1qaz@WSX@tcp(storage-manager-mysql:3306)/storage?parseTime=true
      - name: VOLUME_KUBE_STORAGECLASS
        value: heketi-storageclass
      - name: VOLUME_SIZE
        value: '30'
      - name: VOLUMES_POOL_SIZE
        value: '2'
      image: '[[ registry_release ]]/storage-manager:v1.4.2'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 4500
        protocol: TCP
    controller:
      replica: 1
    pod:
      serviceAccountName: admin
    schedule:
      antiaffinity:
        pod:
          terms:
          - selector:
              labels:
                caicloud-app: storage-manager
            topologyKey: kubernetes.io/hostname
            weight: 100
          type: Prefered
      labels:
        caicloud-app: storage-manager
    services:
    - name: storage-manager
      ports:
      - port: 4500
        protocol: TCP
      type: ClusterIP
    type: Deployment
