_config:
  _metadata:
    description: elasticsearch-v5.6.3
    name: elasticsearch
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v5.6.3
  controllers:
  - containers:
    - env:
      - name: NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: CLUSTER_NAME
        value: esdblogging
      - name: ES_JAVA_OPTS
        value: -Xms2g -Xmx2g
      - name: EXPECTED_NODES
        value: 3
      image: '[[ g_registry_prefix_release ]]/elasticsearch:v5.6.3'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: elasticsearch
        path: /data
      ports:
      - port: 9200
        protocol: TCP
      - port: 9300
        protocol: TCP
      resources:
        limits:
          cpu: 2000m
          memory: 8Gi
        requests:
          cpu: 100m
          memory: 4Gi
      securityContext:
        capabilities:
          add:
          - IPC_LOCK
          - SYS_RESOURCE
        privileged: true
    controller:
      replica: 3
    services:
    - name: elasticsearch
      ports:
      - port: 9200
        protocol: TCP
      type: ClusterIP
    - name: elasticsearch-discovery
      ports:
      - port: 9300
        protocol: TCP
      type: ClusterIP
    type: StatefulSet
    volumes:
    - name: elasticsearch
      source:
        medium: ''
      type: Scratch
