_config:
  _metadata:
    description: devops-admin-v0.4.0-beta.0
    name: devops-admin
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.4.0-beta.0
  controllers:
  - containers:
    - env:
      - name: CYCLONE_SERVER
        value: http://cyclone-server:7099
      - name: STORAGE_ADMIN_SERVER
        value: storage-admin:2333
      - name: CLUSTER_ADMIN_SERVER
        value: cds-server:9000
      - name: MONGO_SERVERS
        value: devops-admin-mongo:27017
      - name: CARGO_ADMIN_SERVER
        value: cargo-admin:8080
      image: '[[ g_registry_prefix_release ]]/devops-admin:v0.4.0-beta.0'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 7088
        protocol: TCP
    controller:
      replicas: 1
    services:
    - name: devops-admin
      ports:
      - port: 7088
        protocol: TCP
        targetPort: 7088
      type: ClusterIP
    type: Deployment
