_config:
  _metadata:
    description: hodor-v1.0.0
    name: hodor
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v1.0.2"
  controllers:
  - containers:
    - env:
      - name: OIDC_ISSUER
        value: http://[[ kube_apiserver_endpoint_ip ]]:32000
      - name: OIDC_CLIENT_ID
        value: caicloud
      image: '[[ registry_release ]]/hodor:v1.0.2'
      imagePullPolicy: IfNotPresent
      mounts:
      - name: hodor
        path: /app/etc/config.yaml
        subpath: config.yaml
    controller:
      replica: 3
    pod:
      annotations:
      - key: prometheus.io/port
        value: '8080'
      - key: prometheus.io/scrape
        value: 'true'
    services:
    - name: hodor-nodeport
      ports:
      - nodePort: 30069
        port: 8080
        protocol: TCP
        targetPort: 8080
      type: NodePort
    - name: hodor
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      type: ClusterIP
    volumes:
    - name: hodor
      source:
        items:
        - key: hodor.yaml
          path: config.yaml
        target: hodor
      type: Config
    configs:
    - name: hodor
      data:
      - key: hodor.yaml
        value: |
          service:
            path: "./hodor"
          plugin:
            path: "./plugins"
          http:
            port: 8080
          middlewares:
          - name: "normalizer"
          - name: "logger"
          - name: "auth"
            config:
              authn:
                oidc:
                  clientID: caicloud
                  issuer: http://[[ kube_apiserver_endpoint_ip ]]:32000
                basic:
                  cauth:
                    url: http://dex-cauth:8080
              authz:
                cauth:
                  url: http://dex-cauth:8080
          - name: "license"
            config:
              endpoint: "http://license:4243/api/stat"
              ttl: 1m
          - name: "metrics"
    type: Deployment
