_config:
  _metadata:
    description: statistician-v0.0.7
    name: statistician
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: v0.0.7
  controllers:
  - containers:
    - image: '[[ g_registry_prefix_release ]]/statistician:v0.0.7'
      imagePullPolicy: IfNotPresent
    controller:
      replicas: 1
      strategy:
        surge: 1
        unavailable: 0
    services:
    - name: statistician
      ports:
      - port: 8080
        protocol: TCP
      type: ClusterIP
    type: Deployment
