_config:
  _metadata:
    description: kibana-logging-5.6.3
    name: logging-kibana
    namespace: kube-system
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "5.6.3-upgrade"
  controllers:
  - containers:
    - env:
      - name: ELASTICSEARCH_URL
        value: http://elasticsearch:9200
      - name: XPACK_MONITORING_ENABLED
        value: 'false'
      - name: XPACK_SECURITY_ENABLED
        value: 'false'
      image: '[[ registry_release ]]/kibana:5.6.3'
      imagePullPolicy: IfNotPresent
      ports:
      - port: 5601
        protocol: TCP
      resources:
        limits:
          cpu: 2000m
          memory: 2Gi
        requests:
          cpu: 100m
          memory: 100Mi
    services:
    - name: kibana-logging
      ports:
      - port: 5601
        nodePort: 32103
        protocol: TCP
        targetPort: 5601
      type: NodePort
    type: Deployment
