_config:
  _metadata:
    description: application-controller
    name: application-controller
    namespace: kube-system
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v0.1.0-alpha.1"
  controllers:
  - containers:
    - image: '[[ registry_release ]]/application-controller:v0.1.0-alpha.1'
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 200Mi
    controller:
      replica: 1
    type: Deployment
