_config:
  _metadata:
    description: application-admission
    name: application-admission
    namespace: kube-system
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v0.2.0-alpha.0"
  controllers:
  - containers:
    - image: '[[ registry_release ]]/application-admission:v0.2.0-alpha.0'
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 200m
          memory: 200Mi
    controller:
      replica: 1
    type: Deployment
    services:
    - name: application-admission
      ports: 
      - port: 443
        protocol: TCP
        targetPort: 443
      type: ClusterIP
