_config:
  _metadata:
    description: monitoring-operator-v0.1.4
    name: monitoring-operator
    namespace: default
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v0.1.5"
  controllers:
  - containers:
    - args:
      - --clusterAdminAddr=cluster-admin:2233
      - --mongodbURL=[[ platform_mongo_host ]]
      image: '[[ registry_release ]]/monitoring-operator:v0.1.5'
      imagePullPolicy: IfNotPresent
    controller:
      replica: 1
      strategy:
        surge: 1
        unavailable: 0
    type: Deployment
