_config:
  _metadata:
    description: monitoring-operator-v0.1.3
    name: monitoring-operator
    template:
      type: template.caicloud.io/application
      version: 1.0.0
    version: "v0.1.3"
  controllers:
  - containers:
    - args:
      - --clusterAdminAddr=cluster-admin:2233
      - --mongodbURL=mongodb://monitoring-admin-mongo:27017
      image: '[[ registry_release ]]/monitoring-operator:v0.1.3'
      imagePullPolicy: IfNotPresent
    controller:
      replica: 1
      strategy:
        surge: 1
        unavailable: 0
    type: Deployment
