apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgcmVjZWl2ZXI6ICJudWxsIgogIGdyb3VwX2J5OgogIC0gY2FpY2xvdWRfdWlkCiAgLSBjYWljbG91ZF9ydWxlX2lkCiAgZ3JvdXBfd2FpdDogMzBzCiAgZ3JvdXBfaW50ZXJ2YWw6IDVtCiAgcmVwZWF0X2ludGVydmFsOiAzaAogIHJvdXRlczoKICAtIHJlY2VpdmVyOiBhcmNoaXZlCiAgICBncm91cF93YWl0OiAzMHMKICAgIG1hdGNoX3JlOgogICAgICBjYWljbG91ZF91aWQ6IC4qCiAgICBjb250aW51ZTogdHJ1ZQpyZWNlaXZlcnM6Ci0gbmFtZTogYXJjaGl2ZQogIHdlYmhvb2tfY29uZmlnczoKICAtIHVybDogaHR0cDovL2FsZXJ0LW5vdGlmaWVyOjUwMDEvYXBpL3YwLjEvYXJjaGl2ZQotIG5hbWU6ICJudWxsIgogIHdlYmhvb2tfY29uZmlnczoKICAtIHVybDogaHR0cDovL2FsZXJ0LW5vdGlmaWVyOjUwMDEvYXBpL3YwLjEvYXJjaGl2ZQo=
kind: Secret
metadata:
  name: alertmanager-caicloud
type: Opaque